version: "3"

services:
  reverse_proxy_example:
    build: ./reverse_proxy_example
    ports:
      - "8080:8080"
    networks:
      testing_network:
        ipv4_address: 172.25.0.2

  python_example:
    build: ./python_example
    ports:
      - "5000:5000"
    networks:
      testing_network:
        ipv4_address: 172.25.0.3

  go_example:
    build: ./go_example
    ports:
      - "5001:5001"
    networks:
      testing_network:
        ipv4_address: 172.25.0.4

networks:
  testing_network:
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/24
