version: "3"

services:
  reverse_proxy_example:
    build: ./reverse_proxy_example
    ports:
      - "8080:8080"
    depends_on: # Docker Compose 會確保在啟動這些服務時，所依賴的服務會在其前被啟動。
      - go_example
      - python_example

  python_example:
    build: ./python_example
    ports:
      - "5000:5000"

  go_example:
    build: ./go_example
    ports:
      - "5001:5001"
