version: "3"

services:
  python_example:
    build: ./python_example
    ports:
      - "5000:5000"
    depends_on:
      - go_example

  go_example:
    build: ./go_example
    ports:
      - "8080:8080"
